name: Build app and deploy to HUAWEIYUN
on:
  #监听push操作
  push:
    branches:
      # mian分支，你也可以改成其他分支
      - master
      - dev
jobs:
  # 任务ID
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
    # 使用别人的action
    - uses: actions/checkout@v2
    # 步骤名称
    - name: npm install
      # 步骤执行指令
      run: npm install
    - name: npm run build
      run: npm run build
    # 命名这个任务为发布Deploy
    - name: Deploy to HUAWEIYUN Server
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
      # Private Key [public key should be add to the list of known hosts in .ssh of ALIYUN_REMOTE_USER] [pem format] [尝试放到root中]
        SSH_PRIVATE_KEY: ${{ secrets.HUAWEIYUN_SERVER_ACCESS_TOKEN }}
      # Remote host
        REMOTE_HOST: ${{ secrets.HUAWEIYUN_SERVER_HOST }}
      # Remote user
        REMOTE_USER: ${{ secrets.HUAWEIYUN_REMOTE_USER }}
      # Remote port
        REMOTE_PORT: 22
      # Source directory
        SOURCE: "dist/"
      # Target directory
        TARGET: ${{ secrets.HUAWEIYUN_TARGET }}